// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLIpghekQIpuNzT3czsnQuh7G-N-bZixI',
    appId: '1:1099133645648:web:a83967767aaf1f2c50b255',
    messagingSenderId: '1099133645648',
    projectId: 'facebook-clone-ade99',
    authDomain: 'facebook-clone-ade99.firebaseapp.com',
    storageBucket: 'facebook-clone-ade99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLIpghekQIpuNzT3czsnQuh7G-N-bZixI',
    appId: '1:1099133645648:android:4638f1834935a1ee50b255',
    messagingSenderId: '1099133645648',
    projectId: 'facebook-clone-ade99',
    storageBucket: 'facebook-clone-ade99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLIpghekQIpuNzT3czsnQuh7G-N-bZixI',
    appId: '1:1099133645648:ios:985973a6f0ccc1f350b255',
    messagingSenderId: '1099133645648',
    projectId: 'facebook-clone-ade99',
    storageBucket: 'facebook-clone-ade99.firebasestorage.app',
    iosBundleId: 'com.example.facebook_clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLIpghekQIpuNzT3czsnQuh7G-N-bZixI',
    appId: '1:1099133645648:ios:985973a6f0ccc1f350b255',
    messagingSenderId: '1099133645648',
    projectId: 'facebook-clone-ade99',
    storageBucket: 'facebook-clone-ade99.firebasestorage.app',
    iosBundleId: 'com.example.facebook_clone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLIpghekQIpuNzT3czsnQuh7G-N-bZixI',
    appId: '1:1099133645648:web:4e9e96ff11dcaccc50b255',
    messagingSenderId: '1099133645648',
    projectId: 'facebook-clone-ade99',
    authDomain: 'facebook-clone-ade99.firebaseapp.com',
    storageBucket: 'facebook-clone-ade99.firebasestorage.app',
  );
}
